/*
 * ChecktonPld API
 *
 * Api para exponer la funcionalidad del ChecktonPld. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using ChecktonPld.RestAPI.Attributes;
using ChecktonPld.RestAPI.Models;
using Microsoft.AspNetCore.Authorization;

namespace ChecktonPld.RestAPI.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public abstract class ChecktonPldApiControllerBase : ControllerBase
    {
        /// <summary>
        /// Valida datos personales con checkton pld
        /// </summary>
        /// <remarks>Valida un cliente con renapo usando api de checkton pld</remarks>
        /// <param name="version">Version of the API to use</param>
        /// <param name="body"></param>
        /// <response code="201">Created</response>
        /// <response code="400">Response to client error satus code</response>
        /// <response code="401">Response to client error satus code</response>
        [HttpPost]
        [Route("/{version:apiVersion}/checktonpld")]
        [ValidateModelState]
        [SwaggerOperation("PostValidaConRenapo")]
        [SwaggerResponse(statusCode: 201, type: typeof(CurpValidacionResult), description: "Created")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "Response to client error status code")]
        [SwaggerResponse(statusCode: 401, type: typeof(InlineResponse400), description: "Response to client error status code")]
        public abstract Task<IActionResult> PostValidaConRenapo([FromRoute] [Required] [RegularExpression("^(?<major>[0-9]+).(?<minor>[0-9]+)$")] string version, [FromBody] ValidacionCurpRequest body);
    }
}
