/*
 * ChecktonPld API
 *
 * Api para exponer la funcionalidad del ChecktonPld. 
 *
 * OpenAPI spec version: 0.1.0
 * Contact: edilberto_diaz14@hotmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace ChecktonPld.RestAPI.Models
{
    /// <summary>
    /// Estructura para validar datos personales en checkton pld
    /// </summary>
    [DataContract]
    public partial class ValidacionCurpRequest : IEquatable<ValidacionCurpRequest>
    { 
        /// <summary>
        /// Gets or Sets Nombre
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// Gets or Sets PrimerApellido
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="primerApellido")]
        public string PrimerApellido { get; set; }

        /// <summary>
        /// Gets or Sets SegundoApellido
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="segundoApellido")]
        public string SegundoApellido { get; set; }

        /// <summary>
        /// Gets or Sets FechaNacimiento
        /// </summary>
        [Required]

        [DataMember(Name="fechaNacimiento")]
        public DateTime? FechaNacimiento { get; set; }

        /// <summary>
        /// Gets or Sets Genero
        /// </summary>
        [Required]

        [DataMember(Name="genero")]
        public GeneroEnum Genero { get; set; }

        /// <summary>
        /// Gets or Sets Estado
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="estado")]
        public string Estado { get; set; }

        /// <summary>
        /// Gets or Sets NombreServicioCliente
        /// </summary>
        [Required]

        [StringLength(100, MinimumLength=1)]
        [DataMember(Name="nombreServicioCliente")]
        public string NombreServicioCliente { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ValidacionCurpRequest {\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  PrimerApellido: ").Append(PrimerApellido).Append("\n");
            sb.Append("  SegundoApellido: ").Append(SegundoApellido).Append("\n");
            sb.Append("  FechaNacimiento: ").Append(FechaNacimiento).Append("\n");
            sb.Append("  Genero: ").Append(Genero).Append("\n");
            sb.Append("  Estado: ").Append(Estado).Append("\n");
            sb.Append("  NombreServicioCliente: ").Append(NombreServicioCliente).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ValidacionCurpRequest)obj);
        }

        /// <summary>
        /// Returns true if ValidacionCurpRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of ValidacionCurpRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ValidacionCurpRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Nombre == other.Nombre ||
                    Nombre != null &&
                    Nombre.Equals(other.Nombre)
                ) && 
                (
                    PrimerApellido == other.PrimerApellido ||
                    PrimerApellido != null &&
                    PrimerApellido.Equals(other.PrimerApellido)
                ) && 
                (
                    SegundoApellido == other.SegundoApellido ||
                    SegundoApellido != null &&
                    SegundoApellido.Equals(other.SegundoApellido)
                ) && 
                (
                    FechaNacimiento == other.FechaNacimiento ||
                    FechaNacimiento != null &&
                    FechaNacimiento.Equals(other.FechaNacimiento)
                ) && 
                (
                    Genero == other.Genero ||
                    Genero != null &&
                    Genero.Equals(other.Genero)
                ) && 
                (
                    Estado == other.Estado ||
                    Estado != null &&
                    Estado.Equals(other.Estado)
                ) && 
                (
                    NombreServicioCliente == other.NombreServicioCliente ||
                    NombreServicioCliente != null &&
                    NombreServicioCliente.Equals(other.NombreServicioCliente)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Nombre != null)
                    hashCode = hashCode * 59 + Nombre.GetHashCode();
                    if (PrimerApellido != null)
                    hashCode = hashCode * 59 + PrimerApellido.GetHashCode();
                    if (SegundoApellido != null)
                    hashCode = hashCode * 59 + SegundoApellido.GetHashCode();
                    if (FechaNacimiento != null)
                    hashCode = hashCode * 59 + FechaNacimiento.GetHashCode();
                    if (Genero != null)
                    hashCode = hashCode * 59 + Genero.GetHashCode();
                    if (Estado != null)
                    hashCode = hashCode * 59 + Estado.GetHashCode();
                    if (NombreServicioCliente != null)
                    hashCode = hashCode * 59 + NombreServicioCliente.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ValidacionCurpRequest left, ValidacionCurpRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ValidacionCurpRequest left, ValidacionCurpRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
